@hostname = localhost
@port = 8080
@Controller = Auth
@baseUrl = http://{{hostname}}:{{port}}/api/{{Controller}}

POST {{baseUrl}}
Content-Type: application/json

{
  "userName": "Gandalf2_O_Cinzento",
  "email": "gandalf2@rpgdex.com",
  "password": "SenhaMagica777!"
}

###
POST {{baseUrl}}/Login
Content-Type: application/json

{
  "email": "gandalf@rpgdex.com",
  "password": "SenhaMagica777!"
}
