@hostname = localhost
@port = 32768
@Controller = Auth
@baseUrl = http://{{hostname}}:{{port}}/api/{{Controller}}

POST {{baseUrl}}
Content-Type: application/json

{
  "userName": "Gandalf3_O_Cinzento",
  "email": "gandalf3@rpgdex.com",
  "password": "SenhaMagica777!"
}

###
POST {{baseUrl}}/Login
Content-Type: application/json

{
  "email": "gandalf@rpgdex.com",
  "password": "SenhaMagica777!"
}

###
POST http://localhost:32768/api/Character
Content-Type: application/json

{
  "Name": "Gandalf",
  "Description": "Istar (Mago) e Portador de Narya",
  "Attributes": [
    { "Name": "Inteligência", "Value": "20" },
    { "Name": "Sabedoria", "Value": "19" }
  ],
  "UserId": "13f0a0e0-91e7-495b-bdae-15fbc58e52e6",
  "Skills": [
    { "Name": "Arcanismo", "Value": 10 },
    { "Name": "História", "Value": 8 }
  ]
}

### Listar Personagens
GET http://localhost:32770/api/Character
Accept: application/json

### GetById

GET http://localhost:32768/api/Character/f53a860b-393b-4daf-b46d-3bd7ebdd3c24
Accept: application/json

### Put

PUT {{baseUrl}}
Content-Type: application/json

{
  "id": "2e79bb57-d92e-453e-a142-c690479bf364",
  "iconPath": "/images/icons/king.png",
  "name": "Aragornteg (Rei Elessar)",
  "description": "Coroado Rei de Gondor e Arnor.",
  "attributes": [
    { "name": "Força", "value": "20" },
    { "name": "Carisma", "value": "19" }
  ],
  "skills": [
    { "name": "Liderança", "value": 10 },
    { "name": "Percepção", "value": 15 }
  ]
}

### Delete

DELETE {{baseUrl}}/f53a860b-393b-4daf-b46d-3bd7ebdd3c24
Accept: application/json