@hostname = localhost
@port = 32768
### 32772

@Controller = Auth
@baseUrl = http://{{hostname}}:{{port}}/api/{{Controller}}

### Ta adicionando mesmo com usuario invalido
POST {{baseUrl}}
Content-Type: application/json

{
  "Name": "Gandalf",
  "Description": "Istar (Mago) e Portador de Narya",
  "Attributes": [
    { "Name": "Inteligência", "Value": "20" },
    { "Name": "Sabedoria", "Value": "19" }
  ],
  "UserId": "13f0a0e0-91e7-495b-bdae-15fbc58e52e6",
  "Skills": [
    { "Name": "Arcanismo", "Value": 10 },
    { "Name": "História", "Value": 8 }
  ]
}
###

POST {{baseUrl}}/Login
Content-Type: application/json

{
  "email": "gandalf@rpgdex.com",
  "password": "SenhaMagica777!"
}
###

POST {{baseUrl}}/RefreshToken
Content-Type: application/json

{
  "AccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxM2YwYTBlMC05MWU3LTQ5NWItYmRhZS0xNWZiYzU4ZTUyZTYiLCJ1bmlxdWVfbmFtZSI6IkdhbmRhbGZfT19DaW56ZW50byIsImVtYWlsIjoiZ2FuZGFsZkBycGdkZXguY29tIiwianRpIjoiMmE1NjkxYTYtM2FhOC00YmVhLTg0N2YtM2QyYjM4ZTJhZGVjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRGVmYXVsdCIsImV4cCI6MTc3NjY5MDc4NSwiaXNzIjoiUnBnRGV4LkF1dGhTZXJ2ZXIiLCJhdWQiOiJScGdEZXguV2ViQVBJIn0.0JXhVn7gOwqNAk90-v72F8zOSaB0122zHhIxUK31hlo",
  "RefreshToken": "L09cpjs4N7zfNz6zmwPoEx1oVFfYuRECdZGccmmKZVNawpKBKyjU/Y1znBcetgrpNttGPZ5s8DTYtw0mAQpNuA=="
}

### Listar Personagens
GET {{baseUrl}}
Accept: application/json

### GetById

GET {{baseUrl}}/f53a860b-393b-4daf-b46d-3bd7ebdd3c24
Accept: application/json

### Put

PUT {{baseUrl}}
Content-Type: application/json

{
  "id": "2e79bb57-d92e-453e-a142-c690479bf364",
  "iconPath": "/images/icons/king.png",
  "name": "Aragornteg (Rei Elessar)",
  "description": "Coroado Rei de Gondor e Arnor.",
  "attributes": [
    { "name": "Força", "value": "20" },
    { "name": "Carisma", "value": "19" }
  ],
  "skills": [
    { "name": "Liderança", "value": 10 },
    { "name": "Percepção", "value": 15 }
  ]
}

### Delete

DELETE {{baseUrl}}/f53a860b-393b-4daf-b46d-3bd7ebdd3c24
Accept: application/json